WebApp_Security/WebApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Data.Account;

namespace WebApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountController : ControllerBase
    {
        private readonly SignInManager<User> _signInManager;

        public AccountController(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }

        public async Task<IActionResult> ExternalLoginCallback()
        {
            var loginInfo = await _signInManager.GetExternalLoginInfoAsync();
            var emailClaim = loginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
            var userClaim = loginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);

            if(emailClaim != null && userClaim != null)
            {
                var user = new User { Email = emailClaim.Value, UserName = userClaim.Value };
                await _signInManager.SignInAsync(user, false);
            }

            return RedirectToPage("/Index");
        }
    }
}

WebApp_Security/WebApp/Pages/Account/AuthenticatorWithMFASetup.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QRCoder;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.Drawing.Imaging;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    [Authorize]
    public class AthenticatorWithMFASetupModel : PageModel
    {
        private readonly UserManager<User> _usermanager;

        [BindProperty]
        public SetupMFAViewModel VM { get; set; }

        [BindProperty]
        public bool Succeeded { get; set; }

        public AthenticatorWithMFASetupModel(UserManager<User> usermanager)
        {
            _usermanager = usermanager;
            VM = new SetupMFAViewModel();
            Succeeded = false;
        }

        public async Task OnGetAsync()
        {
            var user = await _usermanager.GetUserAsync(base.User);
            await _usermanager.ResetAuthenticatorKeyAsync(user);
            var key = await _usermanager.GetAuthenticatorKeyAsync(user);
            VM.Key = key;
            VM.QRCodeBytes = GenerateQRCodeBytes("Wep App", key, user.Email);

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var user = await _usermanager.GetUserAsync(base.User);
            if(await _usermanager.VerifyTwoFactorTokenAsync(user,
                _usermanager.Options.Tokens.AuthenticatorTokenProvider,
                VM.SecurityCode))
            {
                await _usermanager.SetTwoFactorEnabledAsync(user, true);
                Succeeded = true;
            }
            else
            {
                ModelState.AddModelError("AuthenticatorSetup", "Something went wrong with authenticator setup.");
            }

            return Page();
        }

        private Byte[] GenerateQRCodeBytes(string provider, string key, string userEmail)
        {
            var qrCodeGenerator = new QRCodeGenerator();
            var qrCodeData = qrCodeGenerator.CreateQrCode(
                $"otpauth://totop/{provider}:{userEmail}?secret={key}&issuer={provider}",
                QRCodeGenerator.ECCLevel.Q);

            var qrCode = new QRCode(qrCodeData);
            var qrCodeImage = qrCode.GetGraphic(20);

            return BitmapToByteArray(qrCodeImage);
        }

        private Byte[] BitmapToByteArray(Bitmap image)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                image.Save(ms, ImageFormat.Png);
                return ms.ToArray();
            }
        }
    }

    public class SetupMFAViewModel
    {
        public string Key { get; set; }

        [Required]
        [Display(Name ="Security Code")]
        public string SecurityCode { get; set; }

        public Byte[] QRCodeBytes { get; set; }
    }
}

WebApp_Security/WebApp/Pages/Account/ConfirmEmail.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<User> _usermanager;

        [BindProperty]
        public string Message { get; set; }

        public ConfirmEmailModel(UserManager<User> usermanager)
        {
            _usermanager = usermanager;
        }
        public async Task<IActionResult> OnGetAsync(string userId, string token)
        {
            var user = await _usermanager.FindByIdAsync(userId);
            if (user is not null)
            {
                var result = await _usermanager.ConfirmEmailAsync(user, token);
                if (result.Succeeded)
                {
                    Message = "Email successfully confirmed, now you can try to login.";
                    return Page();
                }
            }

            Message = "Failed to validate Email.";
            return Page();
        }
    }
}

WebApp_Security/WebApp/Pages/Account/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<User> _signInMAnager;

        [BindProperty]
        public CredentialViewModel Credential { get; set; }

        [BindProperty]
        public IEnumerable<AuthenticationScheme> ExternalLoginProviders { get; set; }

        public LoginModel(SignInManager<User> signInMAnager)
        {
            _signInMAnager = signInMAnager;
        }


        public async Task OnGet()
        {
            ExternalLoginProviders = await _signInMAnager.GetExternalAuthenticationSchemesAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await _signInMAnager.PasswordSignInAsync(Credential.Email,
                Credential.Password,
                Credential.RememberMe,
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            } 
            else
            {
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("/Account/LoginTwoFactorWithAuthenticator", new
                    {
                        RememberMe = Credential.RememberMe
                    });
                }

                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login", "You are locked out !");
                }
                else
                {
                    ModelState.AddModelError("Login", "Failed to Login...");

                }
            }

            return Page();
        }

        public IActionResult OnPostLoginExternally(string provider)
        {
            var properties = _signInMAnager.ConfigureExternalAuthenticationProperties(provider, null);

            properties.RedirectUri = Url.Action("ExternalLoginCallback", "Account");

            return Challenge(properties, provider);
        }
    }

    public class CredentialViewModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set;}
    }
}

WebApp_Security/WebApp/Pages/Account/LoginTwoFactor.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using WebApp.Data.Account;
using WebApp.Services;

namespace WebApp.Pages.Account
{
    public class LoginTwoFactorModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly IEmailService _emailService;
        private readonly SignInManager<User> _signInManager;

        [BindProperty]
        public EmailMFA EmailMFA { get; set; }

        public LoginTwoFactorModel(UserManager<User> userManager, 
            IEmailService emailService,
            SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _emailService = emailService;
            _signInManager = signInManager;

            EmailMFA = new EmailMFA();
        }
        public async Task OnGetAsync(string email, bool rememberMe)
        {
            var user = await _userManager.FindByEmailAsync(email);

            EmailMFA.SecurityCode = String.Empty;
            EmailMFA.RememberMe = rememberMe;

            var securityCode = await _userManager.GenerateTwoFactorTokenAsync(user, "Email");
            await _emailService.SendAsync("admin@web-app.com",
                email,
                "My Web App's OTP",
                $"Please visit use this code as the OTP: {securityCode}");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await _signInManager.TwoFactorSignInAsync("Email", EmailMFA.SecurityCode, EmailMFA.RememberMe, false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login2FA", "You are locked out !");
                }
                else
                {
                    ModelState.AddModelError("Login2FA", "Failed to Login...");

                }
            }

            return Page();
        }
    }

    public class EmailMFA
    {
        [Required]
        [Display(Name ="Security Code")]
        public string SecurityCode { get; set; }
        public bool RememberMe { get; set; }
    }
}

WebApp_Security/WebApp/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    public class LoginTwoFactorWithAuthenticatorModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;

        [BindProperty]
        public AuthenticatorMFA AuthenticatorMFA { get; set; }

        public LoginTwoFactorWithAuthenticatorModel(SignInManager<User> signInManager)
        {
            AuthenticatorMFA = new AuthenticatorMFA();
            AuthenticatorMFA.RememberMe = false;
            _signInManager = signInManager;
        }
        public void OnGet(bool rememberMe)
        {
            AuthenticatorMFA.SecurityCode = string.Empty;
            AuthenticatorMFA.RememberMe = rememberMe;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await _signInManager.TwoFactorAuthenticatorSignInAsync(
                AuthenticatorMFA.SecurityCode,
                AuthenticatorMFA.RememberMe, 
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Authenticator2FA", "You are locked out !");
                }
                else
                {
                    ModelState.AddModelError("Authenticator2FA", "Failed to Login...");

                }
            }

            return Page();
        }
    }

    public class AuthenticatorMFA
    {
        [Required]
        [Display(Name ="Code")]
        public string SecurityCode { get; set; }

        public bool RememberMe { get; set; }
    }
}

WebApp_Security/WebApp/Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;

        public LogoutModel(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }
 
        public async Task<IActionResult> OnPostAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Account/Login");
        }
    }
}

WebApp_Security/WebApp/Pages/Account/UserProfile.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    [Authorize]
    public class UserProfileModel : PageModel
    {
        private readonly UserManager<User> _userManager;

        [BindProperty]
        public UserProfileViewModel UserProfile { get; set; }

        [BindProperty]
        public string SuccessMessage { get; set; }

        public UserProfileModel(UserManager<User> userManager)
        {
            _userManager = userManager;
            UserProfile = new UserProfileViewModel();
            SuccessMessage = string.Empty;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            SuccessMessage = string.Empty;

            var (user, departmentClaim, positionClaim) = await GetUserInfosAsync();

            UserProfile.Email = User.Identity.Name;
            UserProfile.Department = departmentClaim?.Value;
            UserProfile.Position = positionClaim?.Value;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            try
            {
                var (user, departmentClaim, positionClaim) = await GetUserInfosAsync();
                await _userManager.ReplaceClaimAsync(user, departmentClaim, new Claim(departmentClaim.Type, UserProfile.Department));
                await _userManager.ReplaceClaimAsync(user, positionClaim, new Claim(positionClaim.Type, UserProfile.Position));
            }
            catch
            {
                ModelState.AddModelError("UserProfile", "Error occured when saving user profile.");
            }

            SuccessMessage = "The user profile is saved sucessfully.";


            return Page();
        }

        private async Task<(Data.Account.User, Claim, Claim)> GetUserInfosAsync()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var claims = await _userManager.GetClaimsAsync(user);
            var departmentClaim = claims.FirstOrDefault(x => x.Type == "Department");
            var positionClaim = claims.FirstOrDefault(x => x.Type == "Position");

            return (user, departmentClaim, positionClaim);
        }
    }

    public class UserProfileViewModel
    {
        public string Email { get; set; }

        [Required]
        public string Department { get; set; }

        [Required]
        public string Position { get; set; }
    }
}

WebApp_Security/WebApp/Pages/Account/AuthenticatorWithMFASetup.cshtml
@page
@model WebApp.Pages.Account.AthenticatorWithMFASetupModel
@{
}

<h3>Step 1</h3>

<p>
    Please scan the QR Ccode or enter the Key to your Authentificator App: 
</p>
<p>
    <img src="@string.Format("data:image/png;base64,{0}", 
    Convert.ToBase64String(Model.VM.QRCodeBytes))" width="300" height="300" alt="qr code" />
</p>
<p>
        <b>@Model.VM.Key</b>
</p>
<br />

<h3>Step 2</h3>
<p>
    Please enter the code from your authenticator App:
</p>

<form method="post">
    @if (Model.Succeeded)
    {
        <div class="alert alert-success" role="alert">
            The anthenticator is successfully setup.
        </div>
    }
    <div class="text-danger" asp-validation-summary="All"></div>
        
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="VM.SecurityCode"></label>
        </div>
        <div class="col-8">
            <input type="text" asp-for="VM.SecurityCode" class="form-control" />
        </div>
        <span class="text-danger col" asp-validation-for="VM.SecurityCode"></span>
    </div>

    <div class="mb-3 row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Verify" />
        </div>
        <div class="col-8">
            <input type="hidden" asp-for="VM.Key" />
            <input type="hidden" asp-for="VM.QRCodeBytes" />
        </div>
    </div>
</form>

WebApp_Security/WebApp/Pages/Account/ConfirmEmail.cshtml
@page
@model WebApp.Pages.Account.ConfirmEmailModel
@{
}

<p>
    @Model.Message
</p>

WebApp_Security/WebApp/Pages/Account/Login.cshtml
@page
@model WebApp.Pages.Account.LoginModel
@{
}

<p>
    <h3>User Login</h3>
</p>

<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Credential.Email"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="Credential.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Credential.Email"></span>
        </div>
        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Credential.Password"></label>
            </div>
            <div class="col">
                <input type="password" asp-for="Credential.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Credential.Password"></span>
        </div>
        <div class="row form-check mb-2">
            <div class="col-2">
                <input type="checkbox" asp-for="Credential.RememberMe" class="form-check-input" />
                <label class="form-check-label" asp-for="Credential.RememberMe"></label>
            </div>
            <div class="col">

            </div>
        </div>
        <div class="mb-2 row">
            <div class="col-1">
                <input type="submit" class="btn btn-primary" value="Login" />
            </div>
            <div class="col">
                <a asp-page="/Account/Register" class="btn btn-outline-dark" >Register ?</a>
            </div>
        </div>
        <br />
        <p>
            Social Media Logins:
            <div class="mb-3">
                @foreach(var provider in Model.ExternalLoginProviders)
                {
                    <button type="submit" asp-page-handler="LoginExternally" name="provider" value="@provider.Name" class="btn btn-primary">Login with @provider.DisplayName</button>
                }
            </div>
        </p>
    </form>
</div>

WebApp_Security/WebApp/Pages/Account/LoginTwoFactor.cshtml
@page
@model WebApp.Pages.Account.LoginTwoFactorModel
@{
}

<p>
    <h3>Please enter the code from your email:</h3>
</p>
<div class="container border" style="padding: 20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="EmailMFA.SecurityCode"></label>
            </div>
            <div class="col-8">
                <input type="text" asp-for="EmailMFA.SecurityCode" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="EmailMFA.SecurityCode"></span>
        </div>

        <div class="mb-3 row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col-8">
                <input type="hidden" asp-for="EmailMFA.RememberMe" />
            </div>
        </div>
    </form>
</div>

WebApp_Security/WebApp/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml
@page
@model WebApp.Pages.Account.LoginTwoFactorWithAuthenticatorModel
@{
}

<p>
    <h3>Please enter the code from your authenticator app:</h3>
</p>
<div class="container border" style="padding: 20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="AuthenticatorMFA.SecurityCode"></label>
            </div>
            <div class="col-8">
                <input type="text" asp-for="AuthenticatorMFA.SecurityCode" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="AuthenticatorMFA.SecurityCode"></span>
        </div>

        <div class="mb-3 row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col-8">
                <input type="hidden" asp-for="AuthenticatorMFA.RememberMe" />
            </div>
        </div>
    </form>
</div>

WebApp_Security/WebApp/Pages/Account/Logout.cshtml
@page
@model WebApp.Pages.Account.LogoutModel
@{
}

WebApp_Security/WebApp/Pages/Account/Register.cshtml
@page
@model WebApp.Pages.Account.RegisterModel
@{
}

<p>
    <h3>User Registration</h3>
</p>

<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Email"></label>
            </div>
            <div class="col-8">
                <input type="text" asp-for="RegisterViewModel.Email" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="RegisterViewModel.Email"></span>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Password"></label>
            </div>
            <div class="col-8">
                <input type="password" asp-for="RegisterViewModel.Password" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="RegisterViewModel.Password"></span>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Department"></label>
            </div>
            <div class="col-8">
                <input type="password" asp-for="RegisterViewModel.Department" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="RegisterViewModel.Department"></span>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Position"></label>
            </div>
            <div class="col-8">
                <input type="password" asp-for="RegisterViewModel.Position" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="RegisterViewModel.Position"></span>
        </div>
        <div class="mb-2 row">
            <div class="col-10">
            </div>
            <div class="col text-center">
                <input type="submit" class="btn btn-primary" value="Register" />
            </div>
        </div>
    </form>
</div>

WebApp_Security/WebApp/Pages/Account/UserProfile.cshtml
@page
@model WebApp.Pages.Account.UserProfileModel
@{
}

 <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="UserProfile.Email"></label>
            </div>
            <div class="col-8">
                <input readonly type="text" asp-for="UserProfile.Email" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="UserProfile.Email"></span>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="UserProfile.Department"></label>
            </div>
            <div class="col-8">
                <input type="password" asp-for="UserProfile.Department" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="UserProfile.Department"></span>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="UserProfile.Position"></label>
            </div>
            <div class="col-8">
                <input type="password" asp-for="UserProfile.Position" class="form-control" />
            </div>
            <span class="text-danger col" asp-validation-for="UserProfile.Position"></span>
        </div>
        <div class="mb-2 row">
            <div class="col-10">
            </div>
            <div class="col text-center">
                <input type="submit" class="btn btn-primary" value="Save" />
            </div>
        </div>
    </form>
@if (!string.IsNullOrWhiteSpace(Model.SuccessMessage))
{
    <div class^="alert alert-success" role="alert">
        @Model.SuccessMessage
    </div>
}