M2i_ASPNetCore/Banque.ASPNetCoreMVC/Models/ErrorViewModel.cs
using System;

namespace Banque.ASPNetCoreMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

M2i_ASPNetCore/Banque.ASPNetCoreMVC/Controllers/BankController.cs
using Banque.Classes;
using Banque.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Banque.ASPNetCoreMVC.Controllers
{
    public class BankController : Controller
    {
        public IActionResult Index(string accountId)
        {
            if (int.TryParse(accountId, out int id))
            {
                Account account = BankContext.Instance.Accounts.Include(a=>a.Client).Include(a=>a.Operations).FirstOrDefault(a => a.Id == id);
                if (account != null)
                {
                    return View(account);
                }
            }

            return View();
        }

        public IActionResult NewAccount()
        {
            List<Client> clients = BankContext.Instance.Clients.Include(c=>c.Accounts).ToList();

            return View(clients);
        }

        public IActionResult SubmitAccount(string accountName, string accountClientId)
        {
            

            Client accountClient = BankContext.Instance.Clients.FirstOrDefault(c => c.Id == int.Parse(accountClientId));

            Account account = new Account()
            {
                Name = accountName,
                CreatedAt = DateTime.Now,
                Client = accountClient
            };

            accountClient.Accounts.Add(account);

            BankContext.Instance.Accounts.Add(account);
            BankContext.Instance.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult EditAccount(int id)
        {
            Account account = BankContext.Instance.Accounts.Include(a => a.Client).Include(a => a.Operations).FirstOrDefault(a => a.Id == id);

            return View(account);
        }

        public IActionResult RemoveAccount(int id)
        {
            Account account = BankContext.Instance.Accounts.FirstOrDefault(a => a.Id == id);

            if (account != null)
            {
                BankContext.Instance.Accounts.Remove(account);
                BankContext.Instance.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult NewClient()
        {
            return View();
        }

        public IActionResult SubmitClient(Client client)
        {
            BankContext.Instance.Clients.Add(client);
            BankContext.Instance.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult EditClient(int id, string firstname, string lastname, string email, string phone)
        {
            Client client = BankContext.Instance.Clients.Include(c=>c.Accounts).FirstOrDefault(c => c.Id == id);

            if (client != null)
            {
                client.Firstname = firstname;
                client.Lastname = lastname;
                client.Email = email;
                client.Phone = phone;

                BankContext.Instance.Clients.Update(client);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoveClient(int id)
        {
            Client client = BankContext.Instance.Clients.FirstOrDefault(c => c.Id == id);

            if (client != null)
            {
                BankContext.Instance.Clients.Remove(client);
                BankContext.Instance.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult NewOperation(int id)
        {
            Account account = BankContext.Instance.Accounts.Include(a => a.Client).Include(a => a.Operations).FirstOrDefault(a => a.Id == id);

            return View(account);
        }

        public IActionResult SubmitOperation(int accountId, string operationAmount, string operationType)
        {

            Account account = BankContext.Instance.Accounts.Include(a => a.Client).Include(a => a.Operations).FirstOrDefault(a => a.Id == accountId);

            Operation operation;

            if (operationType == "withdrawal")
            {
                operation = new Operation()
                {
                    Amount = -(decimal.Parse(operationAmount)),
                    Date = DateTime.Now,
                    Account = account,
                };
            }
            else
            {
                operation = new Operation()
                {
                    Amount = (decimal.Parse(operationAmount)),
                    Date = DateTime.Now,
                    Account = account,
                };
            }

            account.Operations.Add(operation);
            BankContext.Instance.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

M2i_ASPNetCore/Banque.ASPNetCoreMVC/Controllers/ChuckController.cs
using Banque.ASPNetCoreMVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace Banque.ASPNetCoreMVC.Controllers
{
    public class ChuckController : Controller
    {
        private ToolsService _toolsService;
        private CheckService _checkService;

        public ChuckController(ToolsService toolsService, CheckService checkService)
        {
            _toolsService = toolsService;
            _checkService = checkService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Chucked(string s)
        {
            return new ContentResult() { Content = _toolsService.ConvertToChuckNorrisCode(s) };
        }

        public IActionResult CheckPass(string s)
        {
            return new ContentResult() { Content = _checkService.CheckPassword(s) };
        }
    }
}

M2i_ASPNetCore/Banque.ASPNetCoreMVC/Controllers/HomeController.cs
using Banque.ASPNetCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Banque.ASPNetCoreMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

M2i_ASPNetCore/Banque.ASPNetCoreMVC/Views/Bank/Index.cshtml
@using Banque.Classes
@*
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	Layout = "_BankLayout";
	Account account = Model as Account;
}

@if (account == null)
{
	<div>
		<form asp-controller="Bank" asp-action="Index">
			<input type="text" name="accountId" placeholder"Account ID" />
			<button type="submit">Rechercher</button>
		</form>
	</div>
}
else
{
	<div>
		<form asp-controller="Bank" asp-action="Index">
			<input type="text" name="accountId" placeholder"Account ID" />
			<button type="submit">Rechercher</button>
		</form>
	</div>

	<div>
		<h2>Account N°@account.Id</h2>
		<div>
			<span>Owner: @($"{account.Client.Firstname} {account.Client.Lastname}")</span>
			<span>Name: @account.Name</span>
			<span>Date of creation: @account.CreatedAt.ToString("d")</span>
		</div>
		<h3>Operations</h3>
		<table>
			<thead>
				<tr>
					<th>Id</th>
					<th>Date</th>
					<th>Amount</th>
				</tr>
			</thead>
			<tbody>
				@foreach(var op in account.Operations)
				{
					<tr>
						<td>@op.Id</td>
						<td>@op.Date.ToString("d")</td>
						<td>@op.Amount</td>
					</tr>
				}
			</tbody>
		</table>
		<a asp-controller="Bank" asp-action="NewOperation" asp-route-id="@account.Id">Make new Operation</a>
	</div>
}

M2i_ASPNetCore/Banque.ASPNetCoreMVC/Views/Bank/NewAccount.cshtml
@using Banque.Classes
@*
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	Layout = "_BankLayout";
	var clients = Model as List<Client>;
}

<div>
	<form asp-action="SubmitAccount" asp-controller="Bank">
		<h2>Create new account</h2>
		<input type="text" placeholder"Account name" name="accountName" />
		<label>Owner: </label>
		<select name="accountClientId">
			@foreach (var client in clients)
			{
				<option value="@client.Id">@($"{client.Firstname} {client.Lastname}")</option>
			}
		</select>
		<button type="submit">Create account</button>
	</form>
</div>

M2i_ASPNetCore/Banque.ASPNetCoreMVC/Views/Bank/NewOperation.cshtml
@using Banque.Classes
@*
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	var account = Model as Account;
}

<h2>New Operation for @account.Name.ToUpper()</h2>
<form asp-action="SubmitOperation" asp-controller="Bank" asp-route-accountId="@account.Id">
	<input type="text" placeholder="Amount" name="OperationAmount" />
	<label>Operation Type: </label>
	<select name="operationType">
		<option value="withdrawal">Withdrawal</option>
		<option value="deposit">Deposit</option>
	</select>

	<button type="submit">Confirm</button>
</form>

M2i_ASPNetCore/Banque.ASPNetCoreMVC/Views/Shared/_BankLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bank Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Bank" asp-action="Index">Bank Home</a>
                <a class="navbar-brand" asp-area="" asp-controller="Bank" asp-action="NewAccount">Create Account</a>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

M2i_ASPNetCore/Banque.ASPNetCoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Banque.ASPNetCoreMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Banque.ASPNetCoreMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Banque.ASPNetCoreMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>