M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Models/ErrorViewModel.cs
namespace M2i_ASP_Ads.ASPMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Controllers/ApiOfferController.cs
using M2i_ASP_Ads.Repositories;
using M2iASP_Ads.Classes;
using Microsoft.AspNetCore.Mvc;

namespace M2i_ASP_Ads.ASPMVC.Controllers;

[Route("/api/v1")]
public class ApiOfferController : Controller
{
    private IWebHostEnvironment _env;
    private IRepository<Offer> _offerRepository;

    public ApiOfferController(IWebHostEnvironment env, IRepository<Offer> offerRepository)
    {
        _env = env;
        _offerRepository = offerRepository;
    }
    
    [HttpGet("/{offerId}")]
    public IActionResult Get(int offerId)
    {
        return Ok(_offerRepository.Get(offerId));
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        return Ok(_offerRepository.GetAll());
    }

    [HttpPost]
    public IActionResult Post([FromForm] IFormFile[] offerImages, [FromForm] Offer offer)
    {
        string wwwRootPath = _env.WebRootPath;
            foreach (var image in offerImages)
            {
                string path = Path.Combine(wwwRootPath, "img", image.FileName);
                using Stream stream = System.IO.File.Create(path);
                image.CopyTo(stream);
                string basePath = "img/" + image.FileName;
                offer.Images.Add(new AdImage() {Path = basePath, Offer = offer});
            }

            if (_offerRepository.Save(offer))
            {
                return Ok(new {Message = "Offer added!"});
            }
            else
            {
                return NotFound(new {Message = "Cannot add this offer..."});
            }



    }
}

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using M2i_ASP_Ads.ASPMVC.Models;

namespace M2i_ASP_Ads.ASPMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Controllers/OfferController.cs
using M2i_ASP_Ads.Repositories;
using M2iASP_Ads.Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using M2i_ASP_Ads.ASPMVC.Services;

namespace M2i_ASP_Ads.ASPMVC.Controllers
{
    public class OfferController : Controller
    {
        private IWebHostEnvironment _env;
        private IRepository<Offer> _offerRepository;
        private LoginService _loginService;
        private FavoriteService _favoriteService;

        public OfferController(IWebHostEnvironment env, IRepository<Offer> offerRepository,
            LoginService loginService, FavoriteService favoriteService)
        {
            _env = env;
            _offerRepository = offerRepository;
            _loginService = loginService;
            _favoriteService = favoriteService;
        }

        public IActionResult List()
        {
            return View(_offerRepository.GetAll());
        }

        public IActionResult Filter(string filter)
        {
            return View("List", (_offerRepository.Search(x => x.Title == filter || x.Description == filter)));
        }

        public IActionResult Details(int id)
        {
            return View(_offerRepository.Get(id));
        }

        public IActionResult New()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult SubmitUser(User user)
        {
            _loginService.Login(user.UserName, user.Password);

            return RedirectToAction("List");
        }

        public IActionResult Logout()
        {
            _loginService.Logout();
                
            return RedirectToAction("List");
        }

        public IActionResult AddFav(int id)
        {
            _favoriteService.AddFavorite(id);

            return RedirectToAction("List");
        }

        public IActionResult RemFav(int id)
        {
            _favoriteService.RemoveFavorite(id);

            return RedirectToAction("List");
        }

        public IActionResult GetFavs()
        {
            return RedirectToAction("List", _favoriteService.GetFavorites());
        }

        public IActionResult SubmitOffer(Offer offer, IFormFile[] offerImages)
        {
            bool isConnected = Request.HttpContext.Session.GetString("connected") == "yes";

            if (isConnected)
            {
                string wwwRootPath = _env.WebRootPath;
                foreach (var image in offerImages)
                {
                    string path = Path.Combine(wwwRootPath, "img", image.FileName);
                    using Stream stream = System.IO.File.Create(path);
                    image.CopyTo(stream);
                    string basePath = "img/" + image.FileName;
                    offer.Images.Add(new AdImage() {Path = basePath, Offer = offer});
                }

                _offerRepository.Save(offer);

                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("List");
            }
        }
    }
}

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Views/Offer/Details.cshtml
@*
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	@model Offer
	Layout = "_AdsLayout";
	@inject FavoriteService _favoriteService;

}
<div class="row">
	<div class="col p-1">
		<div class="row">
			<div class="col">
				<h2>@Model.Title</h2>
			</div>
			<div class="col">
				<h3>@Model.Price.ToString("C", CultureInfo.CurrentCulture)</h3>
			</div>
		</div>


		<div class="row">
			@Model.Description
		</div>

		<div class="row">
			@if (_favoriteService.GetFavorites().Contains(Model))
			{
				<a asp-controller="Offer" asp-action="RemFav" asp-route-id="@Model.Id">Retirer des favoris</a>
			}
			else
			{
				<a asp-controller="Offer" asp-action="AddFav" asp-route-id="@Model.Id">Ajouter aux favoris</a>

			}
		</div>
	</div>
	<div class="col p-1">
		<h3>Images</h3>
		<div class="row">
			@foreach (var image in Model.Images)
			{
				<div class="col">
					<img src="~/@image.Path" alt="Image-@image.Id" class="img-thumbnail rounded">
				</div>
			}
		</div>

	</div>
</div>

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Views/Offer/List.cshtml
@*
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	@model List<Offer>
	Layout = "_AdsLayout";
	}

<form asp-action="Filter" asp-controller="Offer">
	<div class="row">
		<input type="text" name="filter" placeholder="Description or Title"/> 
	</div>
	<button type="submit">Filter</button>
</form>


<div class="row">
	<h2>Offer List</h2>
</div>

@foreach (var offer in Model)
{
	<div class="row p-1">
		<div class="col">
			<a asp-action="Details" asp-controller="Offer" asp-route-id="@offer.Id"><img src="~/@offer.Images.First()?.Path" alt="Offer image" class="rounded img-thumbnail"></a>

		</div>
		<div class="col-6">
			<h3>@offer.Title</h3>
			<p>@offer.Description.Substring(0,(offer.Description.Length > 99 ? 99 : offer.Description.Length)) <a asp-action="Details" asp-controller="Offer" asp-route-id="@offer.Id">(See more...)</a> </p>
		</div>
		<div class="col text-center">
			@offer.Price.ToString("C", CultureInfo.CurrentCulture)
		</div>
	</div>
}
<div class="row p-1">
	<a class="btn btn-secondary" asp-action="New" asp-controller="Offer">New offer</a>

</div>

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Views/Offer/Login.cshtml
@{
    Layout = "_AdsLayout";
}

<form asp-controller="Offer" asp-action="SubmitUser">
    <div class="row mg-1">
        <input type="text" name="username" placeholder="Username"/>
    </div>
    <div class="row mg-1">
        <input type="text" name="password" placeholder="Password"/>
    </div>
    <div class="row">
            <button class="btn btn-primary" type="submit">Submit</button>
    </div>
</form>

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Views/Offer/New.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_AdsLayout";
}

<form asp-action="SubmitOffer" asp-controller="Offer" enctype="multipart/form-data">
    <div class="row p-1">
    <input type="text" name="title" placeholder="Title" />
    </div>
        <div class="row p-1">
    <input type="text" name="price" placeholder="Price" />
    </div>
        <div class="row p-1">
    <input type="text" name="description" placeholder="Description" />
    </div>
        <div class="row p-1">
    <input type="file" multiple name="offerImages" accept="image/jpg, image/jpeg, image/png" />
    </div>
    <div class="row mg-1">
    <button class="btn btn-primary" type="submit">Send</button>

    </div>
</form>

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Views/Shared/_AdsLayout.cshtml
@inject LoginService _loginService;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Offer App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/M2i_ASP_Ads.ASPMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Offer" asp-action="List">Offer List</a>
            @if(_loginService.IsLogged())
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Offer" asp-action="Logout">Logout</a>

                } 
                else
                {
                <a class="navbar-brand" asp-area="" asp-controller="Offer" asp-action="Login">Login</a>
                }
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

M2i_ASP_Ads/M2i_ASP_Ads.ASPMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - M2i_ASP_Ads.ASPMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/M2i_ASP_Ads.ASPMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">M2i_ASP_Ads.ASPMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - M2i_ASP_Ads.ASPMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>